### ISSUE TITLE
finetune-to-livedoor-corpusのノートブックでValueError: test_size=3.001358 should be smaller than 1.0 or be an integerになる

### ISSUE THREAD

**Issue by ycat3** [yoheikikuta/bert-japanese#10]
共有、有難うございます。日本語bertの参考にしてます。
実行すると以下のセルでエラーが発生します。
実行環境は
Ubuntu18.04
python3.7.3
tensorflow 1.13.1
GPU GTX1080Ti
です。

%%time

model = GradientBoostingClassifier(n_estimators=200,
                                   validation_fraction=len(train_df)/len(dev_df),
                                   n_iter_no_change=5,
                                   tol=0.01,
                                   random_state=23)

### 1/5 of full training data.
# model = GradientBoostingClassifier(n_estimators=200,
#                                    validation_fraction=len(dev_df)/len(train_df),
#                                    n_iter_no_change=5,
#                                    tol=0.01,
#                                    random_state=23)

model.fit(train_dev_xs_, train_dev_ys)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

~/.pyenv/versions/anaconda3-5.2.0/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py in fit(self, X, y, sample_weight, monitor)
   1408                 train_test_split(X, y, sample_weight,
   1409                                  random_state=self.random_state,
-> 1410                                  test_size=self.validation_fraction))
   1411         else:
   1412             X_val = y_val = sample_weight_val = None

~/.pyenv/versions/anaconda3-5.2.0/lib/python3.7/site-packages/sklearn/model_selection/_split.py in train_test_split(*arrays, **options)
   2205         cv = CVClass(test_size=test_size,
   2206                      train_size=train_size,
-> 2207                      random_state=random_state)
   2208 
   2209         train, test = next(cv.split(X=arrays[0], y=stratify))

~/.pyenv/versions/anaconda3-5.2.0/lib/python3.7/site-packages/sklearn/model_selection/_split.py in __init__(self, n_splits, test_size, train_size, random_state)
   1276     def __init__(self, n_splits=10, test_size="default", train_size=None,
   1277                  random_state=None):
-> 1278         _validate_shuffle_split_init(test_size, train_size)
   1279         self.n_splits = n_splits
   1280         self.test_size = test_size

~/.pyenv/versions/anaconda3-5.2.0/lib/python3.7/site-packages/sklearn/model_selection/_split.py in _validate_shuffle_split_init(test_size, train_size)
   1797                 raise ValueError(
   1798                     'test_size=%f should be smaller '
-> 1799                     'than 1.0 or be an integer' % test_size)
   1800         elif np.asarray(test_size).dtype.kind != 'i':
   1801             # int values are checked during split based on the input

ValueError: test_size=3.001358 should be smaller than 1.0 or be an integer

**Comment by yoheikikuta** [comment]
これは分子分母逆ですね。ありがとうございます。
修正しました https://github.com/yoheikikuta/bert-japanese/commit/074fe20f33a020769091e1e5552b33867ccbd750

**Comment by yoheikikuta** [comment]
対応済みなので閉じます。
何かあったら reopen してください。
