### ISSUE TITLE
Pretrained modelsをKaggleへ登録しても大丈夫ですか

### ISSUE THREAD

**Issue by vochicong** [yoheikikuta/bert-japanese#16]
Google DriveにあるPretrained modelsをKaggleの public datasetsとして登録して使っても大丈夫でしょうか。

**Comment by vochicong** [comment]
https://www.kaggle.com/vochicong/bert-ja
にアップしました。問題があるようならお知らせください。

**Comment by yoheikikuta** [comment]
はい、大丈夫です。

**Comment by vochicong** [comment]
[finetune-to-livedoor-corpus.ipynb](https://github.com/yoheikikuta/bert-japanese/blob/master/notebook/finetune-to-livedoor-corpus.ipynb)を参考に、Kaggleでライブドアニュースのジャンル予測をやってみました。
- [finetuning kernel](https://www.kaggle.com/vochicong/bert-finetuned-for-livedoor-news-in-japanese)
- [prediction kernel](https://www.kaggle.com/vochicong/bert-predict-livedoor-news-genre-japanese)

また、scriptsも必要なので、本レポジトリのソースコードを[bert-ja-spm](https://www.kaggle.com/vochicong/bert-ja-spm)データセットにに登録しております。
