### ISSUE TITLE
May I know the Specs of PC or cloud's instance this pretraining?

### ISSUE THREAD

**Issue by luvwinnie** [yoheikikuta/bert-japanese#21]
it shows the log you took 5 days to do the pre-training, may I know what is the specs of this pre-training done on?

**Comment by yoheikikuta** [comment]
I used the TPU runtime of Google Colaboratory.
Since a pre-training is computationally expensive, I recommend using TPU.

**Comment by luvwinnie** [comment]
@yoheikikuta So is that means using the free Colaboratory with TPU runtime, preventing the colab to disconnect?

**Comment by yoheikikuta** [comment]
Yup.
We can use Colaboratory for 12 hours, so train a model for 12 hours and save its checkpoints, then continue training using the checkpoints.

**Comment by luvwinnie** [comment]
Ah.... I get it, Thank you for replying. Actually I'm trying to pretrain the model from scratch by modifying your code to be compatible with tensorflow 2.1 ,and testing with GPU to benchmark how long it would take. I would make a PR after i succeed the training.
