### ISSUE TITLE
do_predictフラグを使わない理由はありますか

### ISSUE THREAD

**Issue by miyamonz** [yoheikikuta/bert-japanese#22]
finetune-to-livedoor-courpus.ipynbのPredict using the finetuned modelの章において

```py
result = estimator.predict(input=predict_input_fn)
```
このセルを実行するためにここより上にてrun_classifier.pyと重複するコードが書かれているようです。

しかし、正答率やclassification_reportを見るためであれば、run_classifier.pyのdo_predictフラグで実行した後、出力されたtest_results.tsvを見たほうが楽なように思えます。

こちらに例を用意してみました
https://gist.github.com/miyamonz/0aa8c4aabca21822df685f439167dfc8
手元で動かしましたが、正常に動いているように見えます。
![image](https://user-images.githubusercontent.com/6331508/78214817-12d34f00-74f1-11ea-98eb-142f0bb13afe.png)

機械学習は素人なので、初歩的な勘違い等であったら申し訳ありません。

**Comment by miyamonz** [comment]
finetune-to-livedoor-courpusからリンクされていたcolabのnotebookの方ではdo_predictを使っているのに今気づきました

**Comment by yoheikikuta** [comment]
報告ありがとうございます。
おっしゃる通り `do_predict` を使った方がよくて、基本的には colab で動かすのを想定していたので、 repository に上げてる notebook の方は改修をしていなかったという状況です。

現状は colab の方を見ればいいので直さなくてもいいかなと考えています。
もし PR 送っていただけるようなら反映します。

**Comment by miyamonz** [comment]
ありがとうございます、違いがあるかどうか確信が持てなかったので助かりました。
gistに書いてたものを微修正してPRにしておきました

**Comment by yoheikikuta** [comment]
Merge しました！
PR ありがとうございました！

issue は閉じます。
