### ISSUE TITLE
学習プログラムの再現性を確保する方法について

### ISSUE THREAD

**Issue by FuDaoLiao** [yoheikikuta/bert-japanese#27]
プログラムやドキュメント等を共有いただきありがとうございます。
finetune-to-livedoor-corpus.ipynbでsrc/run_classifier.pyを実行する箇所で学習の再現性を確保したいです。
例えばシード値の固定など、再現性確保のために書き換える必要があるプログラムと処理を教えていただけると幸いです。

現状、以下のプログラムで呼び出しているモジュールに対してシード値を固定していますが、再現性を確保できていない状況です。
- run_classifier.py
  - tensorflow
- tokenization_sentencepiece.py
  - tensorflow
- modeling.py
  - numpy
  - tensorflow
- optimization.py
  - tensorflow

numpy,tensorslowのシード値は以下の方法で固定しています。
```
def fix_seed(seed):
    # Numpy
    np.random.seed(seed)
    # Tensorflow
    tf.compat.v1.set_random_seed(seed)

SEED = 42
fix_seed(SEED)
```

上記のコードは全て、例えば以下のように最初のimportが終わった個所に書いています。
https://github.com/yoheikikuta/bert-japanese/blob/master/src/run_classifier.py#L20

上記以外にシード値固定などの学習の再現性確保に必要なプログラムやモジュールがあればご教示いただけますと幸いです。
また、他にも学習の再現性確保をするための補足事項もあればご教示いただけると幸いです。

**Comment by yoheikikuta** [comment]
返信が遅くなって申し訳ございません。
再現性が担保される仕組みがないまま公開しています（これは単純に当時の私の考慮不足です）。
この辺りが参考になるかもしれません: https://cloud.google.com/tpu/docs/troubleshooting/trouble-tf?hl=ja

この repository では再現性担保までを提供する予定はないので、お手数ですが必要であればご自身でご対応ください。
