### ISSUE TITLE
Which lisence type does your pre-trained model belong to?

### ISSUE THREAD

**Issue by yamazombie** [yoheikikuta/bert-japanese#28]
Hello, @yoheikikuta 

Thank you very much for your great work!
Could you specify the lisence type of your pre-trained model, such as "Apache License 2.0"?
Although you clearly indicate "Apache Lisense 2.0" in GitHub, there seems to be no lisence tag in Hugging Face:
https://huggingface.co/ALINEAR/albert-japanese-v2

Thanks

**Comment by yoheikikuta** [comment]
thanks for your comments.
albert-japanese-v2 in Hugging Face is NOT my pre-trained bert-japanese (albert is a different model from bert).
please ask the author of albert-japanese-v2.

**Comment by yamazombie** [comment]
Oh, I'm sorry for my mistake..
Thank you for your quick reply!
