### ISSUE TITLE
【質問】BERTの中間層の重みベクトルの抽出

### ISSUE THREAD

**Issue by tatz1101** [yoheikikuta/bert-japanese#3]
深層学習の中間層の重み行列を抽出すると、特徴量として用いたり、可視化して内部状態の説明が可能になると思います。
例えばBERTの中間層をもちいて、
下記のようなword2vecの単語マッピングのように、単語の可視化をしたいです
https://qiita.com/Kosuke-Szk/items/d49e2127bf95a1a8e19f
この場合、具体的にBERTのどの中間層の情報を用いれば、
上記の記事のようなマッピングができますでしょうか？
御意見を頂きたいです。宜しくお願い致します。

**Comment by yoheikikuta** [comment]
単語マッピングなら、学習済みの embedding layer の出力を必要な token に対して取得して、それをお好きな方法で低次元化してプロットすればよいと思います。

該当の token の特徴量が一緒に出現する token によって変わる様子などを見たい場合は、Mask Language Model を学習する際の出力を取得して同様のことをすればよいと思います。

このレポジトリで上記実験を提供する予定はないです。

**Comment by yoheikikuta** [comment]
特に進展がない issue なので close します。
