### ISSUE TITLE
finetune-to-livedoor-corpusのノートブックでkeyerrorになる

### ISSUE THREAD

**Issue by lightondust** [yoheikikuta/bert-japanese#4]
共有をありがとうございます。
`bert-japanese/notebook/finetune-to-livedoor-corpus.ipynb`
を実行する際
```
!python3 ../src/run_classifier.py \
  --task_name=livedoor \
  --do_train=true \
  --do_eval=true \
  --data_dir=../data/livedoor \
  --model_file=../model/wiki-ja.model \
  --vocab_file=../model/wiki-ja.vocab \
  --init_checkpoint={PRETRAINED_MODEL_PATH} \
  --max_seq_length=512 \
  --train_batch_size=4 \
  --learning_rate=2e-5 \
  --num_train_epochs=10 \
  --output_dir={FINETUNE_OUTPUT_DIR}
```
で下記のエラーになることがあります。
```
KeyError                                  Traceback (most recent call last)
<ipython-input-113-351daf650d70> in <module>
      2     train_file = os.path.join(FLAGS.output_dir, "train.tf_record")
      3     file_based_convert_examples_to_features(
----> 4         train_examples, label_list, FLAGS.max_seq_length, tokenizer, train_file)
      5     tf.logging.info("***** Running training *****")
      6     tf.logging.info("  Num examples = %d", len(train_examples))

~/bert/bert-japanese/src/run_classifier.py in file_based_convert_examples_to_features(examples, label_list, max_seq_length, tokenizer, output_file)
    362 
    363     feature = convert_single_example(ex_index, example, label_list,
--> 364                                      max_seq_length, tokenizer)
    365 
    366     def create_int_feature(values):

~/bert/bert-japanese/src/run_classifier.py in convert_single_example(ex_index, example, label_list, max_seq_length, tokenizer)
    331   assert len(segment_ids) == max_seq_length
    332 
--> 333   label_id = label_map[example.label]
    334   if ex_index < 5:
    335     tf.logging.info("*** Example ***")

KeyError: '大島優子がここからどう
```

原因は
```
df = pd.DataFrame({'text' : all_text, 'label' : all_label})
```
でdataframeを作っても、カラムの順番が`label`と`text`になって、下記のように`example`がうまく生成されません。
```
{'guid': 'train-3',
 'label': 'ブラックマジックデザイン、...',
 'text_a': 'kaden-channel',
 'text_b': None}
```

御用とお急ぎの方は[run_classifier.py](https://github.com/yoheikikuta/bert-japanese/blob/a0febb2cfb1884abf56b5c6aaa806e3043f94d0/src/run_classifier.py#L244)のところの`text_a`と`label`のところのインデックスをひっくり返せばとりあえずうまくいきますが、notebookの方で
```
df = pd.DataFrame({'text' : all_text, 'label' : all_label})
```
の下に
```
df = df[['text', 'label']]
```
などをして順番を固定した方がいいと思います。

**Comment by lightondust** [comment]
おっしゃる通り。

https://docs.python.org/3.6/whatsnew/3.6.html#new-dict-implementation

> The order-preserving aspect of this new implementation is considered an implementation detail and should not be relied upon (this may change in the future, but it is desired to have this new dict implementation in the language for a few releases before changing the language spec to mandate order-preserving semantics for all current and future Python implementations; this also helps preserve backwards-compatibility with older versions of the language where random iteration order is still in effect, e.g. Python 3.5).

こちらのpythonは3.5でした。

**Comment by yoheikikuta** [comment]
https://github.com/yoheikikuta/bert-japanese/pull/6 でデータを読み込む時に動的に index を取得するようにしたので python 3.6 未満でも適切に動作するようになりました。
