### ISSUE TITLE
SentencePiece tokenizerについて

### ISSUE THREAD

**Issue by lightondust** [yoheikikuta/bert-japanese#5]
文章の分かち書きをSentencePiece tokenizerを使っていますが、Mecabと比較して例えば次のような違いがある

SentencePiece tokenizer:
> /わずか/30/秒/の/短い/映像/ながらも/ス/リル/満/点/に/仕/上がって/いる/
> 絆/をつなぐ/大/切/さを/映画/を通して/伝える/

Mecab
> /わずか/30/秒/の/短い/映像/ながら/も/スリル/満点/に/仕上がっ/て/いる/
> /絆/を/つなぐ/大切/さ/を/映画/を通して/伝える/

「大/切」と「大切」や「満/点」と「満点」の違いはモデルが吸収してくれる期待もできるかもしれませんが、「さを」と「さ/を」や「ス/リル」と「スリル」あたりはモデルのパフォーマンスにクリティカルにな影響を与えうる気がします。

辞書（VOCAB）の更新とTokenizerのカスタマイズ（Mecab、JUMAN++など）を追加学習などで行いたいですが、何かいい方法がありますか。

例えば既存のモデルを再利用して、Tokenizerを変え、VOCABをカスタマイズしてからpretrainしたいですが、`run_pretraining.py`を見てもtokenizeの処理が見当たらなくて。。。

**Comment by yoheikikuta** [comment]
`run_pretraining.py` では tokenize した結果のデータを読み込んで学習するので、ここでは tokenizer は呼ばれていません。pretraining 用のデータを作るところで tokenizer を使って tokenize している部分は以下です。

https://github.com/yoheikikuta/bert-japanese/blob/master/src/create_pretraining_data.py#L190

> 辞書（VOCAB）の更新とTokenizerのカスタマイズ（Mecab、JUMAN++など）を追加学習などで行いたいですが、何かいい方法がありますか。

追加で学習というのはかなり難しいと思います。
tokenize の仕方が異なると token:id のマッピングが変わりますし、追加で辞書に追加するのもその分の embedding を学習して lokkpup table に追加するというのは原理的にはできるはずですが相当大変だと思います。

tokenizer を変えたい、という場合は `FullTokenizer` の tokenizer をお好みのものに差し替えて一から学習するというのが良いと思います。vocab をどのような形式で準備するのかというのはちょっと一口で説明し難いですが、コードを読みばわかると思います（この辺は元の BERT のレポジトリからほぼ変えてません）。

**Comment by yoheikikuta** [comment]
特に進展がない issue なので close します。
何かあれば reopen して議論をお願いします。
